### ISSUE TITLE
Wrong URL query name for some properties

### ISSUE THREAD

**Issue by elisaado** [RikVanHaaren/ah_shop_api#4]
Hi,

I am currently using the API as follows.

```node
client.product().getProductByName('de klok', {property: ["no_alcohol:nee"]}).then(console.log)
```

This code fetches all results for Klok, excluding anything not containing alcohol.

It sadly does not work, as it generates the following URL (decoded) `/zoeken/api/products/search?query=de klok&filters=kenmerk=no_alcohol:nee`

The URL must be (decoded) `/zoeken/api/products/search?query=De Klok&properties=no_alcohol:nee`

Do you have any clue as to what is going on?

With kind regards,

Eli

**Comment by RikVanHaaren** [comment]
Hi Eli

Thank you for reporting this bug.

I released a new version `v1.0.5` where this issue is fixed. I tested youre example request with the same properties and I got the result as expected.

**Expected Result:**
https://www.ah.nl/zoeken?query=de%20klok&kenmerk=no_alcohol%3Anee

**Test Code**
```js
const filter = {
    property: ["no_alcohol:nee"],
}
      
client.product().getProductByName('de klok', filter).then((result) => {
  console.log(result.cards);
});
```

**Result**
```js
[
  { type: 'default', id: 210144, products: [ [Object] ] },
  { type: 'default', id: 183090, products: [ [Object] ] },
  { type: 'default', id: 231219, products: [ [Object] ] }
]
```

Good luck with your project, and if you miss a feature or found another bug please let me know.
